# Generated by Django 4.2 on 2023-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
