# Generated by Django 4.2 on 2023-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0003_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
